networks:
  test_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24 

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    networks:
      test_network:
        ipv4_address: 192.168.100.10  
    tty: true

  host1:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: host1
    networks:
      test_network:
        ipv4_address: 192.168.100.11
    tty: true

